version: '2'
services:
  courses-service:
    image: naglm/courses:latest
    #build: .
    cpu_shares: 100
    mem_limit: 262144000
    container_name: "courses-service"
    restart: on-failure
    ports:
      - "80:8080"
    environment:
      - DB_PORT=3307
      - DB_NAME=courses
      - DB_HOST=mysql
      - MYSQL_USER=courses-user
      - MYSQL_USER_PASSWORD=changeit
      - SPRING_PROFILES_ACTIVE=prod
    logging:
      driver: awslogs
      options:
        awslogs-group: courses-events
        awslogs-region: eu-central-1
        awslogs-stream-prefix: service
