version: '3.5'
services:
#  courses-mysql:
#    image: mysql:latest
#    container_name: "courses-mysql"
#    volumes:
#      - "./db:/var/lib/mysql"
#    ports:
#      - 3307:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=courses
#      - MYSQL_USER=courses-user
#      - MYSQL_PASSWORD=changeit
  courses-postgres:
    image: postgres:latest
    container_name: "courses-postgres"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=courses
    restart: unless-stopped
#   restart: unless-stopped

#  courses-service:
#    build: .
#    links:
#      - courses-mysql
#    container_name: "courses-service"
#    restart: on-failure
#      ports:
#      - "8080:8080"
#      environment:
#      - DB_PORT=3307
#      - DB_NAME=courses
#      - DB_HOST=mysql
#      - MYSQL_USER=courses-user
#      - MYSQL_USER_PASSWORD=changeit
#      - SPRING_PROFILES_ACTIVE=prod
#    depends_on:
#      - courses-mysql
  courses-redis:
    container_name: courses-redis
    image: redis
    ports:
      - "6379:6379"
  courses-elasticsearch:
    container_name: courses-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - discovery.type=single-node
  courses-kibana:
    container_name: courses-kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://courses-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - courses-elasticsearch